### PR TITLE
Added counter

### PR DESCRIPTION
**Pull request by KLVN**
...to see how many users you liked. Mostly you have 150 votes/day but if you're a VIP this counter comes in handy.

### CODE REVIEW

**Comment by danieleargento** [comment]
Thank you for the contribution!

**Comment by KLVN** [comment]
You're welcome!
I tried to change your auto-liker to an auto-visit scripts but I always get an permission-error. Can you give it a try?
```
req = urllib2.Request("https://www.lovoo.com/api_web.php/users/" + matchID + "/visits", "{\"batch\":\"[{\"method\":\"GET\",\"relative_url\":\"/users/" + matchID + "/details\",\"body\":\"userId=" + matchID + "\"},{\"method\":\"GET\",\"relative_url\":\"users/" + matchID + "/pictures\",\"body\":\"userId=" + matchID + "\"},{\"method\":\"POST\",\"relative_url\":\"users/" + matchID + "/visits\",\"body\":\"userId=" + matchID + "\"}]\"}")
```

> {"statusCode":1508,"statusMessage":"Keine Berechtigung","exception":"AccessDeniedHttpException","exceptionMsg":"Access Denied","show":1,"file":"\/var\/www\/lovoo\/src\/Lovoo\/Bundle\/LovooBundle\/Controller\/Controller.php on line 146"}

**Comment by danieleargento** [comment]
Unfortunately i haven't my account anymore, anyway, did you try to use the URL directly instead of using the api_web.php call? I mean, something like: "https://www.lovoo.com/userid=" + matchID

**Comment by KLVN** [comment]
Got it now, still with api_web.php but it's working :)
My old code was calling details, pictures and the visits site all in one but now it's only calling visits

```
req = urllib2.Request("https://www.lovoo.com/api_web.php/users/" + matchID + "/visits?cache=false", "{\"userId\":\"" + matchID + "\",\"category\":\"visits\"}")
```

**Pull request merged**
